### PR TITLE
Add cargo-gtree subcommand for DOT visualization

### PR DESCRIPTION
**Pull request by bsteinb**
I have added another subcommand `cargo-gtree` which reuses most of `cargo-tree` to feed a crate's dependency tree into a `petgraph`, but then uses the `dot` crate to render it into a DOT representation suitable for visualization with the Graphviz package.

I have tried to minimize repetition and hope that the two commands can be kept inside a single repository, but keeping `cargo-gtree` in a separate repository owned by me would also be fine.

### CODE REVIEW

**Comment by sfackler** [comment]
Cool! I think my preference would be for gtree to live in its own repository, but I'd be on board with splitting the graph generation logic out into its own library so that both subcommands could share it.

**Comment by bsteinb** [comment]
Sounds good to me. So I guess the new library would mostly take over the tasks of the `common` and `graph` modules, building a `Graph` from the crate dependencies. Do you want to take a stab at it or should I?

**Comment by sfackler** [comment]
I think I'll take a stab tonight. I need to update the cargo dependency anyway.

**Comment by bsteinb** [comment]
Great! I'll close this then.

**Pull request closed without merging**
