### PR TITLE
Improve compile time

### PR DESCRIPTION
**Pull request by tesuji**
According to measurement on my machine, compilation time go from 45.8s to 25.4s.
More infomation in cargo-timing file: https://gist.github.com/lzutao/4b1a3709d150a6c746fb9b93dcd80076

### CODE REVIEW

**Comment by sfackler** [comment]
Does `cargo install` respect this part of the manifest?

**Comment by tesuji** [comment]
Test locally with `cargo -Ztimings install --path .`, it seems so.
I updated the gist link with new result of `cargo install`.

**Comment by ehuss** [comment]
You might want to consider using this instead of listing explicit packages.

```toml
[profile.release.build-override]
opt-level = 0
```

Also beware, this sets the msrv to 1.41.

**Comment by tesuji** [comment]
> this sets the msrv to 1.41.

@sfackler set CI to nightly. So this shouldn't be problem?

Does `build-override` make crates have `build.rs` (for example FFI crates) no optimization even in release build?
I cannot tell when looking at https://doc.rust-lang.org/nightly/cargo/reference/profiles.html#overrides

**Comment by ehuss** [comment]
> Does `build-override` make build.rs (which FFI crates often be) no optimization even in release build?

I'm not sure I understand the question. The build script and all of its dependencies will be built with opt-level=0.  *Running* the build script will still set the `OPT_LEVEL` environment variable to 2, `build-override` does not affect that.

**Comment by tesuji** [comment]
Sorry for confusing. I was asking that does `build-override` make FFI crates, which often have `build.rs`,
non opimized in release build?

**Comment by ehuss** [comment]
Ah, no.  The crate itself is unaffected and will use opt-level=2.  Cargo doesn't know if something is an ffi crate or not.  `build-override` only affects compilation of the build.rs script itself (and proc macros).

**Comment by tesuji** [comment]
Thanks for explanation. I was misunderstanding that.

**Comment by sfackler** [comment]
Neat, thanks!

**Pull request merged**
