### PR TITLE
Add --all-targets

### PR DESCRIPTION
**Pull request by infinity0**
We're using this for integration testing in debcargo.

### CODE REVIEW

**Comment by infinity0** [comment]
Ping, any news? This should be pretty uncontroversial right?

**Comment by repi** [comment]
This would be great to have!

**Comment by infinity0** [comment]
I've rebased this on the latest master, ping?

**Comment by infinity0** [comment]
Thanks for the merge! I forgot to mention I pushed a couple extra minor features to the master branch that you merged, hope they're OK.

**Pull request merged**
